[package]
name = "strato_core"
description = "Core analysis engine for Strato."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
camino.workspace = true
miette.workspace = true
petgraph.workspace = true
serde.workspace = true
serde_json.workspace = true
strato_cache = { path = "../strato_cache" }
strato_ty_adapter = { path = "../strato_ty_adapter" }
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
