[project]
name = "mypy-strato"
description = "Mypy plugin to catch common asyncio pitfalls."
requires-python = ">=3.11"
authors = [{ name = "Krishna Penukonda", email = "krishna@penukonda.me" }]
readme = "README.md"
license = { text = "MIT" }
dynamic = ["version"]                                                      # Version is automatically determined by build backend
dependencies = [
    "mypy>=1.10.0",
]

[project.optional-dependencies]
dev = ["pytest"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "mypy_strato/__init__.py"
